spring:
  application:
    name: Howzapp

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test-db

  rabbitmq:
    host: ${RABBITMQ_HOST:-localhost}
    port: ${RABBITMQ_PORT:-5672}
    username: ${RABBITMQ_USER:-guest}
    password: ${RABBITMQ_PASSWORD:-guest}

application:
  rabbitmq:
    enabled: ${RABBITMQ_ENABLED:-false}

  jwt:
    secret: V0UgQVJFIE5PVCBUSEUgRkFLRSBPTkUgVE8gT0JGVVNDQVRF
    expiration-minutes: 60

  gcp:
    storage:
      credentials:
        path: "classpath:service-account.json"

  services:
    events:
      url: http://localhost:7070