[versions]
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"

projectApplicationId = "com.techullurgy.howzapp"
projectVersionCode = "1"
projectVersionName = "1.0"
javaVersion = "17"

[plugins]
conventions-android-application = { id = "com.techullurgy.howzapp.conventions.android.application" }
conventions-android-application-compose = { id = "com.techullurgy.howzapp.conventions.android.application.compose" }
conventions-kmp-library = { id = "com.techullurgy.howzapp.conventions.kmp.library" }
conventions-cmp-library = { id = "com.techullurgy.howzapp.conventions.cmp.library" }
conventions-buildkonfig = { id = "com.techullurgy.howzapp.conventions.buildkonfig" }
conventions-room = { id = "com.techullurgy.howzapp.conventions.room" }
conventions-koin-compiler = { id = "com.techullurgy.howzapp.conventions.koin.compiler" }