name: Android Baseline Profile Generator

on:
  workflow_dispatch

jobs:
  bp-generator:
    name: Generate Baseline Profile
    if: ${{ github.repository == 'Mikkareem/howzapp' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: CI gradle wrapper properties
        working-directory: howzapp-app
        run: |
          cat <<EOF > gradle/wrapper/gradle-wrapper.properties
          
          EOF

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes || sdkmanager --licenses || true

      - name: Run Baseline Profile Generator
        working-directory: howzapp-app
        run: |
          ./gradlew :android-benchmarks:pixel6BenchmarkAndroidTest
            --info
            -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
            -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
            -Pandroid.testInstrumentationRunnerArguments.class=com.techullurgy.howzapp.android.benchmark.BaselineProfileGenerator
